Conversion to v11 and added evaluation content/plan
Open-Systems-Pharmacology/Rosuvastatin-Model pull request #3
Opened 2024-08-30 13:20 UTC by ErikssonJ

based on Hanke et al 2021

2024-08-30 13:21 UTC, ErikssonJ commented
Also to be reviewed by @PavelBal?

2024-08-30 15:17 UTC, PavelBal commented
Will do in 2 weeks, I will be ooo.

2024-09-27 10:41 UTC, ErikssonJ commented
> Will do in 2 weeks, I will be ooo.

Hi @PavelBal, just a reminder if you forgot over the OoO.

2024-10-15 14:57 UTC, PavelBal commented
Vmax of OATP1B3 is 0? So it is not used?

![image](https://github.com/user-attachments/assets/09c23046-feb5-47c4-a6af-4b0d247391d5)

2024-10-15 15:03 UTC, PavelBal commented
![image](https://github.com/user-attachments/assets/9d460ffd-3507-4134-b451-db4f25110c36)

Please use the same color for observed data/simulation results that belong together (tissue data have different colors than simulation results). Also I would uncheck the "show in legend" property for the data if they use the same color as the results. Or shorten the names of the data sets. Otherwise the legend is simply too big.

2024-10-15 15:05 UTC, PavelBal requested changes

2024-10-15 15:05 UTC, PavelBal commented on Evaluation/workflow.R
> +}the function body.
`the function body` that seems to be wrong here :)

2024-10-15 15:05 UTC, PavelBal commented on Evaluation/Input/Content/Section1_Introduction.md
> +Rosuvastatin is an inhibitor of the liver 3-hydroxy-3-methyl-glutaryl-coenzyme A reductase (HMG-CoA reductase), and it is prescribed to treat hyperlipidemia. Rosuvastatin is metaboliszed by CYP2C9 to
```suggestion
Rosuvastatin is an inhibitor of the liver 3-hydroxy-3-methyl-glutaryl-coenzyme A reductase (HMG-CoA reductase) and is prescribed to treat hyperlipidemia. Rosuvastatin is metabolized by CYP2C9 to a small extent, transported by OATP1B1 and OATP1B3 into the liver, and subsequently excreted into the bile by BCRP. The renal excretion of rosuvastatin is high, suggesting active tubular secretion (by the transporters OATP2B1, OAT3, and Pgp). The absolute bioavailability of rosuvastatin is about 20%, mainly due to poor absorption. The fraction excreted in feces and urine after an oral dose is about 90% and 10%, respectively, both mainly as parent compound. Rosuvastatin is a substrate of OATP1B1, OATPB1B3, and BCRP and can, therefore, serve as a victim for these transporters in DDI studies. 
```

2024-10-15 15:05 UTC, PavelBal commented on Evaluation/Input/Content/Section1_Introduction.md
> +The herein presented PBPK model of rosuvastatin has been developed using published pharmacokinetic clinical data by Billington et al. 2019 ([Billington 2019](#5-references)), Martin et al. 2003 ([Mar
```suggestion
The herein presented PBPK model of rosuvastatin has been developed using published pharmacokinetic clinical data by Billington et al. 2019 ([Billington 2019](#5-references)), Martin et al. 2003 ([Martin 2003c](#5-references)), Stopfer et al. 2016 ([Stopfer 2016](#5-references)), Stopfer et al. 2018 ([Stopfer 2018b](#5-references)), Wu et al. 2017 ([Wu 2017](#5-references)), Gidal et al. 2017 ([Gidal  2017])(#5-references)), Cooper et al. 2003 ([Cooper 2003a](#5-references)),  Lee et al. 2018 ([Lee 2018](#5-references)) and Gosai et al. 2008 ([Gosai 2008](#5-references)). 
```

2024-10-15 15:05 UTC, PavelBal commented on Evaluation/Input/Content/Section1_Introduction.md
> +- oral absorption with dissolution rate assigned to the Weibull function.
```suggestion
- oral absorption with dissolution rate described by a Weibull function.
```

2024-10-15 15:05 UTC, PavelBal commented on Evaluation/Input/Content/Section2.1_Modeling_Strategy.md
> +A mean model was built based on clinical data from studies with intravenous (Billington et al. 2019 ([Billington 2019](#5-references)), Martin et al. 2003 ([Martin 2003c](#5-references))) and oral ad
```suggestion
A mean model was built based on clinical data from studies with intravenous (Billington et al. 2019 ([Billington 2019](#5-references)), Martin et al. 2003 ([Martin 2003c](#5-references))) and oral administration (Martin et al. 2003 ([Martin 2003c](#5-references)), Stopfer et al. 2016 ([Stopfer 2016](#5-references)), Stopfer et al. 2018 ([Stopfer 2018b](#5-references)), Wu et al. 2017 ([Wu 2017](#5-references)), Gidal et al. 2017 ([Gidal  2017](#5-references)), Cooper et al. 2003 ([Cooper 2003a](#5-references)),  Lee et al. 2018 ([Lee 2018](#5-references)) and Gosai et al. 2008 ([Gosai 2008](#5-references))) of rosuvastatin. The studies reported individual ([Billington 2019](#5-references)) or mean plasma concentrations of rosuvastatin. The study by Billington et al. 2019 also reported individual (n=1) bile fraction of unchanged rosuvastatin as well as tissue concentration in liver and kidney, and the studies by Martin et al. 2003, Stopfer et al. 2016 and Stopfer et al. 2018 reported fraction excreted in urine of unchanged rosuvastatin in addtion to plasma concentrations. The mean PBPK model was developed using a mean individual based on the demographic data for each study. If no demographic data were provided, the following values were used: male, European, 30 years of age, 73 kg body weight, and 176 cm body height. The relative tissue-specific expressions of the enzyme and transporter predominantly being involved in the metabolism/transport of rosuvastatin (CYP2C9, OATP1B1, OATP1B3, BCRP, Pgp and OAT3) were considered ([Meyer 2012](#5-references)). A Weibull function was fitted to describe the oral dissolution of rosuvastatin and the dose was applied as a split dose approach with lag time for the second dose to capture the late Tmax.  
```

2024-10-15 15:05 UTC, PavelBal commented on Evaluation/Input/Content/Section2.1_Modeling_Strategy.md
> +AUClast and Cmax values. In addition sensitivity analyses of included parameter were assessed.
The sensitivity analysis is not shown/discussed in this report? Then do not mention it.

2024-10-15 15:05 UTC, PavelBal commented on Evaluation/Input/Content/Section2.2_Data.md
> +| Weibull shape           | -        | 1.77      | [Seo 2019](#5-references)            | Dissolution profile shape                             |
Weibull shape and time have a source? I assume they were fitted but not taken from a publication?

2024-10-15 15:05 UTC, PavelBal commented on Evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md
> +And several transport protein was implemented into the model via Michaelis-Menten kinetics
```suggestion
The following transport proteins were implemented into the model with the Michaelis-Menten kinetics 
```

2024-10-15 15:05 UTC, PavelBal commented on Evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md
> +For OATP1B1/3 the expression profiles was considered only for OATP1B1 and is based on high-sensitive real-time RT-PCR ([Nishimura 2003](#5-references)). Transporter activity was described as saturabl
For OATP1B1, an alternative reference concentration is used (like in the probenecid model), correct? If so, it must be noted and the reference for the value given.

2024-10-15 15:05 UTC, PavelBal commented on Evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md
> +This is the result of the final parameter identification:
"The following parameters were identified by fitting the model to the data" or something like that.

2024-10-21 07:29 UTC, ErikssonJ commented on Evaluation/Input/Content/Section2.2_Data.md
> +| Weibull shape           | -        | 1.77      | [Seo 2019](#5-references)            | Dissolution profile shape                             |
According to the publication (supplementary material) from Hanke it was taken from the source mentioned. I updated the wording in modeling strategy accordingly.

2024-10-21 08:02 UTC, ErikssonJ commented
> Vmax of OATP1B3 is 0? So it is not used?
> 
> ![image](https://private-user-images.githubusercontent.com/25903040/376670671-09c23046-feb5-47c4-a6af-4b0d247391d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0OTU0NzEsIm5iZiI6MTcyOTQ5NTE3MSwicGF0aCI6Ii8yNTkwMzA0MC8zNzY2NzA2NzEtMDljMjMwNDYtZmViNS00N2M0LWE2YWYtNGIwZDI0NzM5MWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDA3MTkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkN2Q3YWI3NGQzNTNhNzdhY2FlYzRlMTZmY2M1ZmU4ZTIxZThjY2EyNjU0OWZhNzZkMTI2NzJlMTM5ODNjYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x27wZoOHRYqT6h5bYjISS2BD3_NR8TYMr6Z57VhAVkc)

Correct, it is not used, OATP1B1 and 1B3 is lumped together for identifiability - I clarified this in the introduction and removed OATP1B3 from the model.

2024-10-21 11:35 UTC, ErikssonJ commented
Thank you for the review Pavel! I have made the updates accordingly now.

2024-11-04 09:42 UTC, PavelBal approved these changes

2025-05-09 09:18 UTC, Yuri05 commented
@PavelBal @ErikssonJ Can be merged?

2025-05-09 10:50 UTC, ErikssonJ commented
> @PavelBal @ErikssonJ Can be merged?

From my perspective, yes 👍

2025-05-09 11:26 UTC, merged